    <header>
        <a title="logo" href="<?php echo $menu;?>"><img id="logo" src="camera.png" alt="logo" /></a>
        <br>
        <br>
                        
    </header>

        <nav id="menuPerPrivado">
             <ul>
                <li><a href="<?php echo $menu;?>"><span>&nbsp</span><span>FlicktriX</span></a></li>
                <li><a href="<?php echo $menu;?>"><span></span>&nbsp<span>FlicktriX</span></a></li>  
            </ul>
        </nav>