<!DOCTYPE html> 
<html lang="es"> 
<!-- La cabecera --> 
<head> 
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta charset="utf-8" /> 
<meta name="author" content="GrupoX" /> 
<meta name="keywords" content="HTML5, web" /> 
<title> FlicktriX </title>
<link rel="shortcut icon" type="image/x-icon" href="fotoprueba.ico">
<link rel="stylesheet" type="text/css" href="estilo.css"  media=screen>    
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand">
<link rel="alternate stylesheet" type="text/css" href="alternativo1.css" title="Estilo alternativo1">
<link rel="stylesheet" type="text/css" href="imp.css"  media="print">

</head> 